version: '3.4'

services:
  postgresql_database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scraper
    ports:
      - "5432:5432"
    restart: always